[package]
name = "anime_telnet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
image = "0.23.14"
subparse = "0.7.0"
zstd = "0.7"
serde_json = "1"
fast_image_resize = "0.4.0"
anyhow = "1.0.45"

[dependencies.tokio]
version = "1.13"
features = ["io-util","time"]

[dependencies.serde]
version = "1"
features = ["derive"]